# Generated by Django 4.2.2 on 2023-06-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
    ]
